### ISSUE TITLE
Mount external JavaScripts using module system

### ISSUE THREAD

**Issue by Robin-Wils** [kaushalmodi/hugo-search-fuse-js#15]
`hugo mod -get -u` should be `hugo mod get -u` the first command will fail.

**Comment by Robin-Wils** [comment]
Initialize the hugo module system: `hugo mod init github.com/kaushalmodi/hugo-search-fuse-js` is also a required step, which is missing in the readme. After that `go mod tidy` seems to be needed as well.
![image](https://user-images.githubusercontent.com/5617025/151659293-2bbd6269-f83b-4b22-ae00-74f7c328f432.png)
![image](https://user-images.githubusercontent.com/5617025/151659331-7011fe3a-7d70-49ab-9f8a-800bcaca4551.png)

**Comment by Robin-Wils** [comment]
go mod tidy can be skipped it seems.

**Comment by Robin-Wils** [comment]
Nevermind I can't get it working. I will stick with the older version for now.

**Comment by Robin-Wils** [comment]
By the way, it seems like the JavaScript libraries could be linked as module as well, to automatically keep them up to date: https://geeksocket.in/posts/hugo-modules/

**Comment by Robin-Wils** [comment]
![image](https://user-images.githubusercontent.com/5617025/151663650-f6db530f-3e05-4faf-812c-85a994352b4c.png)
For some reason if I import the external libs as modules it works fine, but this module does not. The mounts are optional it should mount everything of this repo by default. Not sure why it does not work

config.toml
```toml
[module]
[[module.imports]]
  path = "github.com/krisk/Fuse"
[[module.mounts]]
  source = 'dist/fuse.min.js'
  target = 'assets/js/libs/fuse.min.js'  

[[module.imports]]
  path = "github.com/julmot/mark.js" 
[[module.mounts]]
  source = 'dist/mark.min.js'
  target = 'assets/js/libs/mark.min.js'  

[[module.imports]]
  path = "github.com/kaushalmodi/hugo-search-fuse-js"
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
````
